# -*- coding: utf-8 -*-
import os
fName='decoded.txt'

a='PE JSD YPDDVNRY UDSGßPX SGO UPW VSXUP; PE JSD EZWWPD, USE TZDX EFSXU CPVI, UPD YSOPD CDüX, USE YPG JSD GXFPX SGO UPX CDüXPX JNPEPX NX ERYZIPDX SGOCPEPFMF, GXU US CNXC UPD EFZDRY SGO EPNXPX VSXCPX DZFPX IPNXPX GXU AVSAAPDFP äCLAFNERY, UPXX UNPEP EADSRYP YSFFP PD HZX EPNXPD WGFFPD CPVPDXF. DNXCE GW UPX SRTPD GXU UNP JNPEP JSDPX CDZßP JäVUPD GXU WNFFPX NX UPX JäVUPDX FNPOP EPPX, QS PE JSD JNDTVNRY YPDDVNRY US UDSGßPX SGO UPW VSXUP! WNFFPX NW EZXXPXERYPNX VSC UZDF PNX SVFPE DNFFPDCGF, HZX FNPOPX TSXäVPX GWCPIPX, GXU HZX UPD WSGPD INE MGW JSEEPD YPDGXFPD JGRYEPX CDZßP TVPFFPXIVäFFPD, UNP EZ YZRY JSDPX, USß TVPNXP TNXUPD GXFPD UPX YöRYEFPX SGODPRYF EFPYPX TZXXFPX; PE JSD SIPD EZ JNVU USDNX, JNP NW FNPOEFPX JSVUP. YNPD ESß PNXP PXFP SGO UPW XPEFP, JPVRYP NYDP QGXCPX SGEIDüFPX WGßFP, SIPD PE JGDUP NYD OSEF MG VSXCJPNVNC, PYP UNP QGXCPX TSWPX, USMG IPTSW ENP EPVFPX IPEGRY; UNP SXUPDX PXFPX ERYJSWWPX VNPIPD NX UPX TSXäVPX GWYPD, SVE USß ENP YNXSGO VNPOPX, ENRY GXFPD PNX TVPPIVSFF MG EPFMPX GXU WNF NYD MG ERYXSFFPDX.PXUVNRY IZDEF PNX PN XSRY UPW SXUPDX. »ANPA, ANPA!« ESCFP PE GXU SVVP PNUZFFPD JSDPX VPIPXUNC CPJZDUPX GXU UNP QGXCPX PXFVPNX EFPRTFPX UPX TZAO YPD SGE'

d={'a': 'p',
 'b': 'k',
 'c': 'g',
 'd': 'r',
 'e': 's',
 'f': 't',
 'g': 'u',
 'h': 'v',
 'i': 'b',
 'j': 'w',
 'k': 'b',
 'l': 'y',
 'm': 'z',
 'n': 'i',
 'o': 'f',
 'p': 'e',
 'q': 'j',
 'r': 'c',
 's': 'a',
 't': 'k',
 'u': 'd',
 'v': 'l',
 'w': 'm',
 'x': 'n',
 'y': 'h',
 'z': 'o'}

try:
    os.remove(fName)
except: 
    pass


f=open(fName,'a+')

c=0
for i in a:
    if i.lower() not in d or i.isspace():
        f.write(i)
        c+=1
        continue
    
    #print(i)
    f.write(d[ a[c].lower() ])
    c+=1


f.close()
